
name: 🚀 pages deploy
on:
  push:
    tags:
    - "v*"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/configure-pages@v6
    - uses: actions/setup-node@v6
      with:
        node-version: "25"

    - run: npm ci
    - run: npm run build -s
    - run: npm test

    - uses: actions/upload-pages-artifact@v5
      with:
        path: "x"

    - uses: actions/deploy-pages@v5
      id: deployment

